name: Build Project
on: [push]
jobs:
  build_artifacts:
    name: Build Artifacts
    runs-on: windows-2019
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Init gradle
        shell: cmd
        run: call gradle init

      - name: Build project
        shell: cmd
        run: call gradle jpackage

      - name: Clean build file
        shell: powershell
        run: call Remove-Item build/jpackage/Process-Scheduling-Simulator/*.ico

      - name: Zipping build result
        uses: papeloto/action-zip@v1
        with:
          files: build/jpackage/Process-Scheduling-Simulator/
          dest: u/Process-Scheduling-Simulator.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            u/Process-Scheduling-Simulator.zip
