name: Upload JavaDoc (main, develop)
on: [ push ]
env:
  GRAPHVIZ_DOT: 'C:\Program Files\Graphviz\bin\dot.exe'

jobs:
  upload-javadoc:
    name: Upload JavaDoc
    runs-on: windows-2022
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Build JavaDoc
        shell: cmd
        run: gradle moduleInfoBackup && gradle javadoc && gradle moduleInfoRestore

      - name: Zipping Docs
        uses: papeloto/action-zip@v1
        with:
          files: build/docs/javadoc/
          dest: ./u/javadoc.zip

      - name: Generate checksum
        shell: pwsh
        run: Get-FileHash ./u/javadoc.zip -Algorithm SHA512 >> ./u/SHA512_CHECKSUM

      - name: Upload doxygen document to server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.abstr.net
          port: 3333
          username: ost10
          password: ${{ secrets.ftp_password }}
          local-dir: './u/'
