name: Upload JavaDoc (main, develop)
on: [push]

jobs:
  build_doxygen:
    name: Upload Doxygen Document
    runs-on: ubuntu-20.04
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Build JavaDoc
        shell: cmd
        run: gradle javadoc

      - name: Zipping Docs
        uses: papeloto/action-zip@v1
        with:
          files: build/docs/
          dest: ./u/javadoc.zip

      - name: Generate checksum
        run: shasum -a 512 ./u/docs.zip >> ./u/SHA512_CHECKSUM

      - name: Upload doxygen document to server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.abstr.net
          port: 3333
          username: ost10
          password: ${{ secrets.ftp_password }}
          local-dir: './u/'
